<?php
declare(strict_types=1);
$paginaAtual = 'rpi';
require __DIR__ . '/rpi_service.php';
function e(string|int|float|null $v): string { return htmlspecialchars((string) $v, ENT_QUOTES, 'UTF-8'); }
function tamanhoLegivel(int $v): string { return $v < 1048576 ? number_format($v / 1024, 1, ',', '.') . ' KB' : number_format($v / 1048576, 1, ',', '.') . ' MB'; }
$mensagem = ''; $erro = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['acao'] ?? '') === 'sincronizar') {
    try { $edicao = rpiSincronizarEImportarMaisRecente(); $mensagem = 'A RPI ' . $edicao['numero'] . ' foi baixada; ' . $edicao['publicacoes_importadas'] . ' publicações novas foram importadas.'; }
    catch (Throwable $excecao) { $erro = $excecao->getMessage(); }
}
$edicoes = rpiCarregarIndice();
?>
<!doctype html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>MarcaFácil | Revista RPI</title><style>
:root{--navy:#111827;--blue:#2563eb;--blue-dark:#1d4ed8;--bg:#f6f8fc;--text:#172033;--muted:#6b7280;--line:#e7eaf0;--green:#147a55;--red:#c73b4b}*{box-sizing:border-box;margin:0;font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}body{min-height:100vh;background:var(--bg);color:var(--text)}.layout{display:grid;grid-template-columns:250px 1fr;min-height:100vh}aside{background:var(--navy);color:#d7deeb;padding:26px 16px;display:flex;flex-direction:column}.brand{padding:0 12px 30px;color:#fff;font-size:21px;font-weight:800;letter-spacing:-.7px}.brand span{color:#78a5ff}.menu-title{color:#8ea0bb;text-transform:uppercase;font-size:10px;letter-spacing:.8px;margin:8px 12px 10px;font-weight:800}nav{display:grid;gap:5px}nav a{text-decoration:none;color:inherit;padding:12px;border-radius:9px;font-size:14px}nav a:hover,nav a.active{background:#263757;color:#fff}.side-note{margin-top:auto;padding:14px;border:1px solid #334155;border-radius:10px;font-size:12px;line-height:1.5}main{width:100%;max-width:1300px;margin:auto;padding:34px 42px}.header{display:flex;justify-content:space-between;align-items:flex-start;gap:24px;margin-bottom:26px}.header h1{font-size:28px;letter-spacing:-.8px}.header p{color:var(--muted);margin-top:7px;line-height:1.5}.button{border:0;background:var(--blue);color:#fff;border-radius:9px;padding:12px 16px;font-size:14px;font-weight:700;cursor:pointer}.button:hover{background:var(--blue-dark)}.card{background:#fff;border:1px solid var(--line);border-radius:16px;padding:24px;box-shadow:0 2px 10px rgba(27,39,65,.03)}.notice{padding:13px 15px;border-radius:10px;margin-bottom:18px;font-size:14px}.success{background:#ecfdf5;color:var(--green);border:1px solid #a7f3d0}.error{background:#fff1f2;color:var(--red);border:1px solid #fecdd3}.info{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:20px 0}.info div{background:#f8faff;border:1px solid #e8edf8;border-radius:12px;padding:16px}.info strong{display:block;font-size:19px;margin-bottom:5px}.info span{color:var(--muted);font-size:13px}.sub{font-size:18px;margin-bottom:5px}.hint{color:var(--muted);font-size:14px;line-height:1.5;margin-bottom:20px}.table-wrap{overflow:auto}.table{width:100%;border-collapse:collapse;font-size:14px}.table th{text-align:left;color:var(--muted);font-size:12px;text-transform:uppercase;letter-spacing:.4px;padding:12px;border-bottom:1px solid var(--line)}.table td{padding:15px 12px;border-bottom:1px solid var(--line)}.tag{background:#eaf1ff;color:#2452aa;border-radius:999px;padding:5px 9px;font-weight:700;font-size:12px}.link{color:var(--blue);font-weight:700;text-decoration:none}.empty{text-align:center;padding:34px;color:var(--muted)}code{background:#f1f5f9;padding:2px 5px;border-radius:4px;color:#334155}@media(max-width:800px){.layout{grid-template-columns:1fr}aside{display:none}main{padding:24px 18px}.header{display:block}.header form{margin-top:16px}.info{grid-template-columns:1fr}}
</style></head><body><div class="layout"><?php require __DIR__ . '/menu.php'; ?><main><div class="header"><div><h1>Revista RPI</h1><p>Baixe e mantenha arquivadas as edições de Marcas da Revista da Propriedade Industrial.</p></div><form method="post"><input type="hidden" name="acao" value="sincronizar"><button class="button" type="submit">Sincronizar edição mais recente</button></form></div><?php if ($mensagem !== ''): ?><div class="notice success"><?= e($mensagem) ?></div><?php endif; ?><?php if ($erro !== ''): ?><div class="notice error"><?= e($erro) ?></div><?php endif; ?><section class="card"><h2 class="sub">Atualização automática</h2><p class="hint">O INPI publica a RPI semanalmente às terças-feiras. Para automatizar neste computador, crie uma tarefa no Agendador do Windows que execute <code>php sincronizar_rpi.php</code> toda terça após a publicação. O script só baixa a edição caso ela ainda não esteja arquivada.</p><div class="info"><div><strong><?= count($edicoes) ?></strong><span>Edições salvas</span></div><div><strong>Terças-feiras</strong><span>Periodicidade oficial</span></div><div><strong>PDF de Marcas</strong><span>Fonte: portal do INPI</span></div></div><h2 class="sub">Edições baixadas</h2><p class="hint">Na próxima etapa, estas edições serão lidas para localizar automaticamente as publicações dos processos cadastrados.</p><div class="table-wrap"><table class="table"><thead><tr><th>RPI</th><th>Data da publicação</th><th>Arquivo</th><th>Tamanho</th><th></th></tr></thead><tbody><?php if ($edicoes === []): ?><tr><td class="empty" colspan="5">Nenhuma edição baixada ainda. Use o botão de sincronização para buscar a mais recente.</td></tr><?php endif; ?><?php foreach ($edicoes as $edicao): ?><tr><td><span class="tag">RPI <?= e($edicao['numero'] ?? '') ?></span></td><td><?= e($edicao['data'] ?? 'Não informada') ?></td><td><?= e($edicao['arquivo'] ?? '') ?></td><td><?= isset($edicao['tamanho']) ? e(tamanhoLegivel((int) $edicao['tamanho'])) : '—' ?></td><td><?php if (!empty($edicao['arquivo'])): ?><a class="link" target="_blank" href="rpis/<?= rawurlencode((string) $edicao['arquivo']) ?>">Abrir PDF</a><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div></section></main></div></body></html>
